services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=school_db'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=toor'
      - 'MYSQL_USER=user'
    ports:
      - '3306'
