spring:
  application:
    name: school-app
  
  # Flyway configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
  
  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # Jackson configuration
  jackson:
    serialization:
      fail-on-empty-beans: false
    date-format: yyyy-MM-dd
    time-zone: UTC
  
  # Docker-support configuration
  docker:
    compose:
      enabled: false
  
  # Actuator configuration
  management:
    endpoints:
      web:
        exposure:
          include: "*"

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /api/v1

# Logging configuration
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    re:
      ermix:
        school_app: DEBUG
